import * as Phaser from 'phaser';

export class AudioManager {
  private scene: Phaser.Scene;
  private sounds: Map<string, Phaser.Sound.BaseSound> = new Map();
  private musicVolume = 0.5;
  private sfxVolume = 0.7;

  constructor(scene: Phaser.Scene) {
    this.scene = scene;
  }

  /**
   * Play sound effect
   */
  playSFX(key: string, volume: number = 1): void {
    // For now, we'll use simple beep sounds generated by Phaser
    // In production, load actual audio files

    if (!this.sounds.has(key)) {
      // Create simple tone using WebAudio (placeholder)
      // TODO: Load actual audio files in preload
    }

    // Play sound
    // this.scene.sound.play(key, { volume: this.sfxVolume * volume });

    // For now, just log
    // console.log(`🔊 Playing SFX: ${key}`);
  }

  /**
   * Play music (loop)
   */
  playMusic(key: string): void {
    // TODO: Load and play background music
    // this.scene.sound.play(key, { volume: this.musicVolume, loop: true });
  }

  /**
   * Stop music
   */
  stopMusic(): void {
    // this.scene.sound.stopAll();
  }

  /**
   * Set music volume
   */
  setMusicVolume(volume: number): void {
    this.musicVolume = Phaser.Math.Clamp(volume, 0, 1);
  }

  /**
   * Set SFX volume
   */
  setSFXVolume(volume: number): void {
    this.sfxVolume = Phaser.Math.Clamp(volume, 0, 1);
  }

  /**
   * Preload audio assets
   */
  preloadAudio(loader: Phaser.Loader.LoaderPlugin): void {
    // TODO: Load audio files
    // loader.audio('shoot', 'assets/audio/shoot.mp3');
    // loader.audio('hit', 'assets/audio/hit.mp3');
    // loader.audio('explosion', 'assets/audio/explosion.mp3');
    // loader.audio('levelup', 'assets/audio/levelup.mp3');
    // loader.audio('boss_music', 'assets/audio/boss_music.mp3');
  }
}
